baseURL = "https://experimental-software.github.io/linux-workshop"
languageCode = "en-gb"
title = "Linux Workshop"
theme = "workshop-materials"

[params]
  subject = "Linux"
  feedbackLink = "https://github.com/experimental-software/linux-workshop/issues/new"
