baseURL = "http://example.org/linux-training"
languageCode = "en-gb"
title = "Linux Workshop"
theme = "workshop-materials"

[params]
  subject = "Linux"
  feedbackLink = "https://github.com/experimental-software/linux-training/issues/new"

